# Generated by Django 2.2 on 2020-08-03 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfTrainer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_handle', models.CharField(max_length=100)),
                ('handle1', models.CharField(max_length=100)),
                ('handle2', models.CharField(max_length=100)),
                ('handle3', models.CharField(max_length=100)),
            ],
        ),
    ]
